app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Route::group(array("before" => "auth"), function()
{
	Route::get('/', 					["as" => "home", 		"uses" => "HomeController@index"]);

	Route::resource('usuarios', 	'UsuarioController');
	Route::resource('mensagens', 	'MensagensController');
	// Route::resource('fotos', 	'FotosController');
	Route::resource('videos', 		'VideosController');
	Route::resource('metas', 		'MetasController');
	Route::resource('performance',  'PerformanceController');
	Route::resource('eventos', 		'EventosController');

	Route::get('usuarios/{id}/professor/{opcao}', 				[ 'as' => 'usuarios.professor', 'uses' => 'UsuarioController@professor']);

	Route::get('fotos', 										[ 'as' => 'fotos.index', 'uses' => 'FotosController@index']);
	Route::get('fotos/album/{id?}', 							[ 'as' => 'fotos.album', 'uses' => 'FotosController@album']);
	Route::post('salva-foto/{tipo}', 							[ 'as' => 'usuario.fotos', 'uses' => 'UsuarioController@salvaFoto']);

	Route::get( 'conhecimento/aluno/{id}', 						[ 'as' => 'performance.aluno', 'uses' => 'PerformanceController@aluno']);
	Route::post('conhecimento/aluno/{id}', 						[ 'as' => 'performance.alunoUpdate', 'uses' => 'PerformanceController@alunoUpdate']);
	Route::get( 'conhecimento/chakra/{aid}/{cid}', 				[ 'as' => 'performance.chakra', 'uses' => 'PerformanceController@show']);
	Route::get( 'conhecimento/chakra/{aid}/{cid}/edit', 		[ 'as' => 'performance.chakra.edit', 'uses' => 'PerformanceController@edit']);
	Route::put( 'conhecimento/chakra/{aid}/{cid}', 				[ 'as' => 'performance.chakra.update', 'uses' => 'PerformanceController@update']);
	Route::post('conhecimento/chakra/{cid}/tecnica', 			[ 'as' => 'performance.chakra.tecnicac', 'uses' => 'PerformanceController@createTecnica']);
	Route::put( 'conhecimento/chakra/{cid}/tecnica/{tid}', 		[ 'as' => 'performance.chakra.tecnicau', 'uses' => 'PerformanceController@updateTecnica']);
	Route::delete('conhecimento/chakra/{cid}/tecnica/{tid}', 	[ 'as' => 'performance.chakra.tecnicad', 'uses' => 'PerformanceController@deleteTecnica']);
	Route::post('conhecimento/chakra/aluno/tecnicas/', 			[ 'as' => 'performance.chakra.tecAluno', 'uses' => 'PerformanceController@tecAluno']);

	Route::get('eventos/calendar/{aid?}', 						[ 'as' => 'eventos.calendar', 'uses' => 'EventosController@calendar']);
	Route::get('eventos/create/{aid?}', 						[ 'as' => 'eventos.createc', 'uses' => 'EventosController@create']);
	Route::get('eventos/edit/{aid}/{id}', 						[ 'as' => 'eventos.editc', 'uses' => 'EventosController@edit']);

	Route::get( 'performance/aluno/{aid?}', 					[ 'as' => 'metas.aluno', 'uses' => 'MetasController@aluno']);
	Route::get( 'performance/create/{tipo}/{aid?}', 			[ 'as' => 'metas.criar', 'uses' => 'MetasController@create']);
	Route::post('performance/{id}/add-foto', 					[ 'as' => 'metas.add-foto', 'uses' => 'MetasController@addFoto']);
	Route::post('performance/{id}/add-nota', 					[ 'as' => 'metas.add-nota', 'uses' => 'MetasController@addNota']);
});

/* ROTAS DE LOGIN, SENHA E CADASTRO */
Route::get('/login', 					["as" => "login", 			"uses" => "LoginController@index"]);
Route::post('/login', 					["as" => "login.validate", 	"uses" => "LoginController@validate"]);
Route::get('/esqueci-a-senha', 			["as" => "login.esqueci", 	"uses" => "LoginController@esqueci"]);
Route::post('/esqueci-a-senha', 		["as" => "login.senha", 	"uses" => "LoginController@enviaSenha"]);
Route::get('/senha/{id}/{token}', 		["as" => "login.reset", 	"uses" => "LoginController@formSenha"]);
Route::post('/senha', 					["as" => "login.atualiza", 	"uses" => "LoginController@validaSenha"]);
Route::get('/logout', 					["as" => "logout", 			"uses" => "LoginController@logout"]);
Route::get('/cadastro', 				["as" => "cadastro", 		"uses" => "LoginController@cadastro"]);
Route::post('/cadastro', 				["as" => "cadastro.save", 	"uses" => "LoginController@cadastroSave"]);

app/models/Meta.php
<?php

use Carbon\Carbon;

class Meta extends Eloquent {

	const TIPO_ASANA = 1;
	const TIPO_RESPIRACAO = 2;
	const TIPO_MEDITACAO = 3;
	const TIPO_LIMPEZA = 4;

	protected $fillable = array('nome', 'meta', 'tipo', 'video', 'foto');

	/*VALIDAÇÃO DOS CADASTROS*/
	public static $rules = array(
		'nome' => 'required',
		'meta' => 'required',
		'tipo' => 'required',
	);

	/*TRANSFORMAÇÃO DAS DATAS*/
	public function getDates()
	{
		return array('created_at','updated_at');
	}

	public function aluno()
	{
		return $this->belongsTo('User','aluno_id');
	}

	public function notas()
	{
		return $this->hasMany('MetaNota','meta_id');
	}

	public function fotos()
	{
		return $this->hasMany('MetaFoto','meta_id');
	}

}

app/controllers/MetasController.php
<?php

class MetasController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		return $this->aluno( $this->user->id );
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function aluno($aid)
	{
		$aluno = User::find($aid);

		$metas = $aluno->metas;

		$posicoes = [];
		$respiracoes = [];
		$meditacoes = [];
		$limpezas = [];

		if ( count( $metas ) ) {
			$posicoes = $metas->filter( function($item){
				return $this->filtraMeta( $item , Meta::TIPO_ASANA );
			});

			$respiracoes = $metas->filter( function($item){
				return $this->filtraMeta( $item , Meta::TIPO_RESPIRACAO );
			});

			$meditacoes = $metas->filter( function($item){
				return $this->filtraMeta( $item , Meta::TIPO_MEDITACAO );
			});

			$limpezas = $metas->filter( function($item){
				return $this->filtraMeta( $item , Meta::TIPO_LIMPEZA );
			});
		}

		return Response::view('metas.index', [
			"aluno"       => $aluno,
			"posicoes"    => $posicoes,
			"respiracoes" => $respiracoes,
			"meditacoes"  => $meditacoes,
			"limpezas"    => $limpezas,
		]);
	}

	private function filtraMeta($meta, $tipo)
	{
		return $meta->tipo == $tipo;
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create($tipo, $aid)
	{
		return Response::view('metas.form');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$validator = Validator::make(Input::all(), Meta::$rules);
		$tipo = Input::get('tipo');

		if ($validator->fails())
		{
			return Redirect::route("metas.criar", [ $tipo, Input::get('aid') ])->withErrors($validator)->withInput( Input::all() );
		}
		else
		{
			// dd("Dados gravados");

			$meta = Meta::create([
				"nome"  => Input::get("nome"),
				"meta"  => Input::get("meta"),
				"video" => Input::get("video"),
				"tipo"  => $tipo,
			]);

			$aluno = User::find( Input::get("aid") );

			if ( Input::hasFile('foto') ) {
				$foto     = Input::file('foto');
				$destino  = Config::get("infinito.UPLOAD_PATH") . "/metas";
				$fileName = 'meta_' . $tipo . "_" . $aluno->id . "_" . $meta->id . "." . $foto->getClientOriginalExtension();
				$foto->move($destino, $fileName);

				$meta->foto = $fileName;
			}

			$meta->aluno()->associate($aluno);
			$meta->save();

			$this->createHistorico(
				"Nova meta! <a href='" . route("metas.aluno", [$aluno->id]) . "'>veja mais</a>",
				"heart",
				$aluno
			);

			return Redirect::route("metas.aluno", [ Input::get('aid') ])->with("message","Meta criada com sucesso");
		}
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function addNota()
	{
		$validator = Validator::make(Input::all(), MetaNota::$rules);
		
		if ($validator->fails())
		{
			return Redirect::route("metas.show", [ Input::get('meta') ])->withErrors($validator)->withInput( Input::all() );
		}
		else
		{
			// dd("Dados gravados");

			$nota = MetaNota::create([
				"descricao"  => Input::get("descricao"),
				"valor"  => Input::get("valor"),
			]);

			$meta = Meta::find( Input::get("meta") );
			$meta->notas()->save($nota);
			$nota->meta()->associate($meta);

			$meta->save();
			$nota->save();

			$this->createHistorico(
				"Nova anotação em meta! <a href='" . route("metas.aluno", [$meta->aluno->id]) . "'>veja mais</a>",
				"flag",
				$meta->aluno
			);

			return Redirect::route("metas.show", [ $meta->id ])->with("message_nota","Nota adicionada com sucesso");
		}
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function addFoto()
	{
		$validator = Validator::make(Input::all(), MetaFoto::$rules);

		if ($validator->fails())
		{
			return Redirect::route("metas.show", [ Input::get('meta') ])->withErrors($validator)->withInput( Input::all() );
		}
		else
		{
			$meta = Meta::find( Input::get("meta") );

			$metaFoto = MetaFoto::create([
				"url"  => uniqid()
			]);

			$foto     = Input::file('imagem');
			$destino  = Config::get("infinito.UPLOAD_PATH") . "/metas/meta_" . $meta->id;
			$fileName = 'meta_' . $metaFoto->id . "." . $foto->getClientOriginalExtension();
			$foto->move($destino, $fileName);

			$metaFoto->url = $fileName;
			$metaFoto->save();

			$meta->fotos()->save($metaFoto);
			$metaFoto->meta()->associate($meta);

			$meta->save();
			$metaFoto->save();

			$this->createHistorico(
				"Nova foto de meta! <a href='" . route("metas.aluno", [$meta->aluno->id]) . "'>veja aqui</a>",
				"picture",
				$meta->aluno
			);

			return Redirect::route("metas.show", [ $meta->id ])->with("message_foto","Foto adicionada com sucesso");
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$meta = Meta::findOrFail($id);

		$fotos = $meta->fotos->sortByDesc('created_at');
		$notas = $meta->notas->sortByDesc('created_at');

		// dd($notas->first());

		return Response::view('metas.item', [
			"meta"  => $meta,
			"notas" => $notas,
			"fotos" => $fotos,
		]);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		return Response::view('metas.form', [
			"meta" => Meta::find($id)
		]);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$validator = Validator::make(Input::all(), Meta::$rules);
		$tipo = Input::get('tipo');

		if ($validator->fails())
		{
			return Redirect::route("metas.criar", [ $tipo, Input::get('aid') ])->withErrors($validator)->withInput( Input::all() );
		}
		else
		{
			$meta = Meta::find($id);
			// dd([$id, $meta]);
			$meta->fill([
				"nome"  => Input::get("nome"),
				"meta"  => Input::get("meta"),
				"video" => Input::get("video"),
			]);

			if ( Input::hasFile('foto') ) {
				$foto     = Input::file('foto');
				$destino  = Config::get("infinito.UPLOAD_PATH") . "/metas";
				$fileName = 'meta_' . $tipo . "_" . $aluno->id . "_" . $meta->id . "." . $foto->getClientOriginalExtension();
				$foto->move($destino, $fileName);

				$meta->foto = $fileName;
			}

			$meta->save();

			return Redirect::route("metas.aluno", [ Input::get('aid') ])->with("message","Meta alterada com sucesso");
		}
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


}

app/views/metas/form.blade.php
@extends('master')

@section('content')
	<div class="metas row">
		<div class="col-xs-12 col-md-8 col-md-offset-2">
			<h1 class="tit-area">Performance</h1>

			@if ( $errors->has() )
			<div class="alert alert-danger alert-dismissable">
				<i class="fa fa-ban"></i>
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				<p><b>Aviso!</b></p>
				@foreach( $errors->all('<p>:message</p>') as $message )
					{{ $message }}
				@endforeach
			</div>
			@endif

			<div class="conteudo-container row">
				@if ( isset($meta) )
				{{ Form::model($meta, array('route' => ['metas.update', $meta->id], 'method' => 'put', 'files' => true)) }}
				{{ Form::hidden('aid', $meta->aluno->id ) }}
				{{ Form::hidden('tipo', $meta->tipo ) }}
				@else
				{{ Form::open(array('route' => array('metas.store'), 'method' => 'post', 'files' => true)) }}
				{{ Form::hidden('aid', Route::input('aid') ) }}
				{{ Form::hidden('tipo', Route::input('tipo') ) }}
				@endif

				<div class="col-xs-12 form-group {{{ $errors->has('nome') ? 'has-error' : '' }}}">
					{{ Form::label("nome", "Nome") }}
					{{ Form::text("nome", Input::old('nome'), array( "class" => "form-control" )) }}
				</div>
				<div class="col-xs-12 form-group {{{ $errors->has('meta') ? 'has-error' : '' }}}">
					{{ Form::label("meta", "Meta") }}
					{{ Form::text("meta", Input::old('meta'), array( "class" => "form-control" )) }}
					<p class="help-block">(Ex. 12 minutos | 0-4-5-3)</p>
				</div>
				<div class="col-xs-12 form-group {{{ $errors->has('video') ? 'has-error' : '' }}}">
					{{ Form::label("video", "Link para vídeo") }}
					{{ Form::text("video", Input::old('video'), array( "class" => "form-control" )) }}
				</div>
				<div class="col-xs-12 form-group {{{ $errors->has('foto') ? 'has-error' : '' }}}">
					{{ Form::label("foto", "Imagem") }}
					{{ Form::file("foto", Input::old('foto'), array( "class" => "form-control" )) }}
				</div>
                    <div class="col-xs-12 form-group">
                        <button class="btn btn-primary btn-flat">SALVAR</button>
                    </div>

				{{ Form::close() }}
			</div>
		</div>
	</div>
@stop

app/views/metas/index.blade.php
@extends('master')

@section('content')
	<div class="metas row">
		<div class="col-xs-12 col-md-8 col-md-offset-2">
			@include('usuarios.imagens')

			<h1 class="tit-area">Performance</h1>

			@if ( Session::has("message") )
				<div class="alert alert-info" role="alert">{{ Session::pull("message") }}</div>
			@endif

			<p>Ásanas - Posições <a href="http://www.vocenoinfinito.com/" target="_blank">(Clique para mais info)</a></p>
			<div class="conteudo-container asanas metas-container flexslider">
				<ul class="slider">
					@foreach ($posicoes as $meta)
					<li class="{{ ( count( $meta->notas ) && $meta->notas->sortByDesc('created_at')->first()->valor == 100 ) ? "concluida" : "" }}">
						<div>
							<a href="{{ route('metas.show', [$meta->id]) }}" data-fancybox-type="iframe" class="link-meta">
								@if ( ! empty($meta->foto) )
								
								<img src="/uploads/metas/{{ $meta->foto }}" alt="">
								@else
								<p class="nome">{{ $meta->nome }}</p>
								@endif
							</a>
							<div class="inferior">
								<div class="posicao">
									@if ( count( $meta->notas ) )
										<div class="percentual" style="width:{{ $meta->notas->sortByDesc('created_at')->first()->valor }}%"></div>
									@else
										<div class="percentual" style="width:0"></div>
									@endif
								</div>
								<p class="meta">{{ $meta->meta }}</p>
							</div>
						</div>
						@if ( $usuario->isProfessor() && $aluno->professor->id == $usuario->id )
							<a href="{{ route('metas.edit', [ $meta->id ]) }}" class="btn btn-link"><i class="glyphicon glyphicon-pencil"></i> Editar</a>
						@endif
					</li>
					@endforeach
					@if ( $usuario->isProfessor() && $aluno->professor->id == $usuario->id )
					<li>
						<div class="adicionar">
							<a href="{{ route('metas.criar', [ 1, Route::input('aid') ]) }}" class="btn btn-primary btn-block">Adicionar meta</a>
						</div>
					</li>
					@endif
				</ul>
			</div>

			<p>Respiração <a href="http://www.vocenoinfinito.com/" target="_blank">(Clique para mais info)</a></p>
			<div class="conteudo-container respiracao metas-container flexslider">
				<ul class="slider">
					@foreach ($respiracoes as $meta)
					<li class="{{ ( count( $meta->notas ) && $meta->notas->sortByDesc('created_at')->first()->valor == 100 ) ? "concluida" : "" }}">
						<div>
							<a href="{{ route('metas.show', [$meta->id]) }}" data-fancybox-type="iframe" class="link-meta">
								<p class="nome">{{ $meta->nome }}</p>
							</a>
							<div class="inferior">
								<div class="posicao">
									@if ( count( $meta->notas ) )
										<div class="percentual" style="width:{{ $meta->notas->sortByDesc('created_at')->first()->valor }}%"></div>
									@else
										<div class="percentual" style="width:0"></div>
									@endif
								</div>
								<p class="meta">{{ $meta->meta }}</p>
							</div>
						</div>
						@if ( $usuario->isProfessor() && $aluno->professor->id == $usuario->id )
							<a href="{{ route('metas.edit', [ $meta->id ]) }}" class="btn btn-link"><i class="glyphicon glyphicon-pencil"></i> Editar</a>
						@endif
					</li>
					@endforeach
					@if ( $usuario->isProfessor() && $aluno->professor->id == $usuario->id )
					<li>
						<div class="adicionar">
							<a href="{{ route('metas.criar', [ 2, Route::input('aid') ]) }}" class="btn btn-primary btn-block">Adicionar meta</a>
						</div>
					</li>
					@endif
				</ul>
			</div>

			<p>Meditação <a href="http://www.vocenoinfinito.com/" target="_blank">(Clique para mais info)</a></p>
			<div class="conteudo-container meditacao metas-container flexslider">
				<ul class="slider">
					@foreach ($meditacoes as $meta)
					<li class="{{ ( count( $meta->notas ) && $meta->notas->sortByDesc('created_at')->first()->valor == 100 ) ? "concluida" : "" }}">
						<div>
							<a href="{{ route('metas.show', [$meta->id]) }}" data-fancybox-type="iframe" class="link-meta">
								<p class="nome">{{ $meta->nome }}</p>
							</a>
							<div class="inferior">
								<div class="posicao">
									@if ( count( $meta->notas ) )
										<div class="percentual" style="width:{{ $meta->notas->sortByDesc('created_at')->first()->valor }}%"></div>
									@else
										<div class="percentual" style="width:0"></div>
									@endif
								</div>
								<p class="meta">{{ $meta->meta }}</p>
							</div>
						</div>
						@if ( $usuario->isProfessor() && $aluno->professor->id == $usuario->id )
							<a href="{{ route('metas.edit', [ $meta->id ]) }}" class="btn btn-link"><i class="glyphicon glyphicon-pencil"></i> Editar</a>
						@endif
					</li>
					@endforeach
					@if ( $usuario->isProfessor() && $aluno->professor->id == $usuario->id )
					<li>
						<div class="adicionar">
							<a href="{{ route('metas.criar', [ 3, Route::input('aid') ]) }}" class="btn btn-primary btn-block">Adicionar meta</a>
						</div>
					</li>
					@endif
				</ul>
			</div>

			<p>Limpeza <a href="http://www.vocenoinfinito.com/" target="_blank">(Clique para mais info)</a></p>
			<div class="conteudo-container limpeza metas-container flexslider">
				<ul class="slider">
					@foreach ($limpezas as $meta)
					<li class="{{ ( count( $meta->notas ) && $meta->notas->sortByDesc('created_at')->first()->valor == 100 ) ? "concluida" : "" }}">
						<div>
							<a href="{{ route('metas.show', [$meta->id]) }}" data-fancybox-type="iframe" class="link-meta">
								<p class="nome">{{ $meta->nome }}</p>
							</a>
							<div class="inferior">
								<div class="posicao">
									@if ( count( $meta->notas ) )
										<div class="percentual" style="width:{{ $meta->notas->sortByDesc('created_at')->first()->valor }}%"></div>
									@else
										<div class="percentual" style="width:0"></div>
									@endif
								</div>
								<p class="meta">{{ $meta->meta }}</p>
							</div>
						</div>
						@if ( $usuario->isProfessor() && $aluno->professor->id == $usuario->id )
							<a href="{{ route('metas.edit', [ $meta->id ]) }}" class="btn btn-link"><i class="glyphicon glyphicon-pencil"></i> Editar</a>
						@endif
					</li>
					@endforeach
					@if ( $usuario->isProfessor() && $aluno->professor->id == $usuario->id )
					<li>
						<div class="adicionar">
							<a href="{{ route('metas.criar', [ 4, Route::input('aid') ]) }}" class="btn btn-primary btn-block">Adicionar meta</a>
						</div>
					</li>
					@endif
				</ul>
			</div>
		</div>
	</div>
@stop

app/views/metas/item.blade.php
@extends('master-lightbox')

@section('content')
	<div class="container-fluid metas">
		<div class="row meta-item metas-container">
			@if ( $meta->tipo == Meta::TIPO_ASANA && ! empty( $meta->foto ) )
			<div class="col-xs-12 col-sm-4 text-center">
				<img src="/uploads/metas/{{ $meta->foto }}" alt="{{ $meta->nome }}">
			</div>
			<div class="col-xs-12 col-sm-6">
			@else
			<div class="col-xs-12 col-sm-6 col-sm-offset-3 meta-nome">
				<h3 class="text-center">{{ $meta->nome }}</h3>
			@endif
				@if ( count( $notas ) && $notas->first()->valor == 100 )
				<div class="concluida">
				@else
				<div>
				@endif

					<div class="posicao">
						@if ( count( $notas ) )
							<div class="percentual" style="width:{{ $notas->first()->valor }}%"></div>
						@else
							<div class="percentual" style="width:0"></div>
						@endif
					</div>
					<p class="meta">{{ $meta->meta }}</p>
				</div>
			</div>

			<div class="col-xs-12">
				@if ( ! empty( $meta->video ) )
					<p class="link-video">
						<a href="{{ $meta->video }}" target="_blank">Clique aqui para ver vídeo exemplo</a>
					</p>
				@endif
			</div>

			@if ( Session::has("message_foto") )
				<div class="col-xs-12">
					<div class="alert alert-info" role="alert">{{ Session::pull("message_foto") }}</div>
				</div>
			@endif

			{{-- LISTAGEM DE FOTOS --}}

			<div class="col-xs-12">

				{{-- @if ( count( $meta->fotos ) ) --}}
					<h3>Fotos:</h3>

					<div class="fotos">
						<ul class="slider">
							@foreach($meta->fotos as $foto)
								<li><a href="/uploads/metas/meta_{{ $meta->id }}/{{ $foto->url }}" class="link-foto">
									<img src="{{ Image::url('/uploads/metas/meta_' . $meta->id .'/'. $foto->url ,140,90,['crop']) }}" alt="{{ $foto->id }}">
								</a></li>
							@endforeach
						</ul>
					</div>
				{{-- @endif --}}
			</div>

			{{-- FORMULÁRIO PARA ADICIONAR FOTOS --}}
			@if ( $errors->has('imagem') )
			<div class="col-xs-12">
				<div class="alert alert-danger alert-dismissable">
					<p><i class="fa fa-ban"></i> <b>Aviso!</b></p>
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					@foreach( $errors->all('<p>:message</p>') as $message )
						{{ $message }}
					@endforeach
				</div>
			</div>
			@endif

			@if ( $usuario->isProfessor() && $meta->aluno->professor->id == $usuario->id )
			<div class="col-xs-12">
				<div class="panel panel-primary">
					<div class="panel-body">
						<p>Selecione uma foto para adicionar a meta</p>
						{{ Form::open(['route' => ['metas.add-foto'], 'method' => 'post', 'files' => true]) }}
						{{ Form::hidden('meta', $meta->id ) }}
						
						<div class="input-group">
							{{ Form::file('imagem', ['class' => 'form-control']) }}
							<span class="input-group-btn">
								{{ Form::submit('Adicionar Foto', ['class' => 'btn btn-warning']); }}
							</span>
						</div>
						{{ Form::close() }}
					</div>
				</div>
			</div>
			@endif

			{{-- LISTAGEM DE NOTAS --}}

			<div class="col-xs-12 notas">
				<h3>Notas:</h3>

				<ul>
					@forelse($notas as $nota)
						<li>{{ $nota->created_at->format('d/m') }} - {{ $nota->descricao }}</li>
					@empty
						<li>Nenhuma nota cadastrada até o momento</li>
					@endforelse
				</ul>
				@if ( $usuario->isProfessor() && $meta->aluno->professor->id == $usuario->id )
				<a href="#add-nota" class="btn btn-primary btn-add-nota">Adicionar nota</a>
				@endif
			</div>

			{{-- FORMULÁRIO PARA ADICIONAR NOTAS --}}

			@if ( $usuario->isProfessor() && $meta->aluno->professor->id == $usuario->id )
				@if ( Session::has("message_nota") )
					<div class="col-xs-12">
						<div class="alert alert-info" role="alert">{{ Session::pull("message_nota") }}</div>
					</div>
				@endif

				@if ( $errors->has('descricao') || $errors->has('valor') )
				<div class="col-xs-12">
					<div class="alert alert-danger alert-dismissable">
						<p><i class="fa fa-ban"></i> <b>Aviso!</b></p>
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						@foreach( $errors->all('<p>:message</p>') as $message )
							{{ $message }}
						@endforeach
					</div>
				</div>
				<div class="col-xs-12 form-nota open">
				@else
				<div class="col-xs-12 form-nota">
				@endif

					<div class="panel panel-primary">
						<div class="panel-body">
							{{ Form::open(['route' => ['metas.add-nota'], 'method' => 'post']) }}
							{{ Form::hidden('meta', $meta->id ) }}
							
							<div class="form-group {{{ $errors->has('descricao') ? 'has-error' : '' }}}">
								{{ Form::label("valor", "Nota (de 0 a 100)") }}
								{{ Form::number("valor", Input::old('valor'), array( "class" => "form-control" )) }}
								{{-- <input id="valor" name="valor" type="range" min="0" max="100" step="1" class="form-control" /> --}}
							</div>
							<div class="form-group {{{ $errors->has('descricao') ? 'has-error' : '' }}}">
								{{ Form::label("descricao", "Descricao") }}
								{{ Form::text("descricao", Input::old('video'), array( "class" => "form-control" )) }}
							</div>
							
							{{ Form::submit('Enviar Nota', ['class' => 'btn btn-warning']); }}
							{{ Form::close() }}
						</div>
					</div>
				</div>
			@endif
		</div>
	</div>
@stop