app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Route::group(array("before" => "auth"), function()
{
	Route::get('/', 					["as" => "home", 		"uses" => "HomeController@index"]);

	Route::resource('usuarios', 	'UsuarioController');
	Route::resource('mensagens', 	'MensagensController');
	// Route::resource('fotos', 	'FotosController');
	Route::resource('videos', 		'VideosController');
	Route::resource('metas', 		'MetasController');
	Route::resource('performance',  'PerformanceController');
	Route::resource('eventos', 		'EventosController');

	Route::get('usuarios/{id}/professor/{opcao}', 				[ 'as' => 'usuarios.professor', 'uses' => 'UsuarioController@professor']);

	Route::get('fotos', 										[ 'as' => 'fotos.index', 'uses' => 'FotosController@index']);
	Route::get('fotos/album/{id?}', 							[ 'as' => 'fotos.album', 'uses' => 'FotosController@album']);
	Route::post('salva-foto/{tipo}', 							[ 'as' => 'usuario.fotos', 'uses' => 'UsuarioController@salvaFoto']);

	Route::get( 'conhecimento/aluno/{id}', 						[ 'as' => 'performance.aluno', 'uses' => 'PerformanceController@aluno']);
	Route::post('conhecimento/aluno/{id}', 						[ 'as' => 'performance.alunoUpdate', 'uses' => 'PerformanceController@alunoUpdate']);
	Route::get( 'conhecimento/chakra/{aid}/{cid}', 				[ 'as' => 'performance.chakra', 'uses' => 'PerformanceController@show']);
	Route::get( 'conhecimento/chakra/{aid}/{cid}/edit', 		[ 'as' => 'performance.chakra.edit', 'uses' => 'PerformanceController@edit']);
	Route::put( 'conhecimento/chakra/{aid}/{cid}', 				[ 'as' => 'performance.chakra.update', 'uses' => 'PerformanceController@update']);
	Route::post('conhecimento/chakra/{cid}/tecnica', 			[ 'as' => 'performance.chakra.tecnicac', 'uses' => 'PerformanceController@createTecnica']);
	Route::put( 'conhecimento/chakra/{cid}/tecnica/{tid}', 		[ 'as' => 'performance.chakra.tecnicau', 'uses' => 'PerformanceController@updateTecnica']);
	Route::delete('conhecimento/chakra/{cid}/tecnica/{tid}', 	[ 'as' => 'performance.chakra.tecnicad', 'uses' => 'PerformanceController@deleteTecnica']);
	Route::post('conhecimento/chakra/aluno/tecnicas/', 			[ 'as' => 'performance.chakra.tecAluno', 'uses' => 'PerformanceController@tecAluno']);

	Route::get('eventos/calendar/{aid?}', 						[ 'as' => 'eventos.calendar', 'uses' => 'EventosController@calendar']);
	Route::get('eventos/create/{aid?}', 						[ 'as' => 'eventos.createc', 'uses' => 'EventosController@create']);
	Route::get('eventos/edit/{aid}/{id}', 						[ 'as' => 'eventos.editc', 'uses' => 'EventosController@edit']);

	Route::get( 'performance/aluno/{aid?}', 					[ 'as' => 'metas.aluno', 'uses' => 'MetasController@aluno']);
	Route::get( 'performance/create/{tipo}/{aid?}', 			[ 'as' => 'metas.criar', 'uses' => 'MetasController@create']);
	Route::post('performance/{id}/add-foto', 					[ 'as' => 'metas.add-foto', 'uses' => 'MetasController@addFoto']);
	Route::post('performance/{id}/add-nota', 					[ 'as' => 'metas.add-nota', 'uses' => 'MetasController@addNota']);
});

/* ROTAS DE LOGIN, SENHA E CADASTRO */
Route::get('/login', 					["as" => "login", 			"uses" => "LoginController@index"]);
Route::post('/login', 					["as" => "login.validate", 	"uses" => "LoginController@validate"]);
Route::get('/esqueci-a-senha', 			["as" => "login.esqueci", 	"uses" => "LoginController@esqueci"]);
Route::post('/esqueci-a-senha', 		["as" => "login.senha", 	"uses" => "LoginController@enviaSenha"]);
Route::get('/senha/{id}/{token}', 		["as" => "login.reset", 	"uses" => "LoginController@formSenha"]);
Route::post('/senha', 					["as" => "login.atualiza", 	"uses" => "LoginController@validaSenha"]);
Route::get('/logout', 					["as" => "logout", 			"uses" => "LoginController@logout"]);
Route::get('/cadastro', 				["as" => "cadastro", 		"uses" => "LoginController@cadastro"]);
Route::post('/cadastro', 				["as" => "cadastro.save", 	"uses" => "LoginController@cadastroSave"]);

app/models/User.php
<?php

use Carbon\Carbon;

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends \Cartalyst\Sentry\Users\Eloquent\User implements RemindableInterface {

	use UserTrait, RemindableTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	protected static $loginAttribute = 'email';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array(
		'password',
		'reset_password_code',
		'activation_code',
		'persist_code',
		'remember_token',
	);

	protected $fillable = array(
		'email', 'professor_id','password','first_name', 'last_name', 'sexo', 'profissao', 'peso', 'altura', 'nacionalidade', 'telefone',
		'estado_civil', 'endereco', 'telefone', 'nacionalidade', 'objetivos', 'facebook',
		'data_nascimento', 'inicio_infinito', 'inicio_yoga', 'observacoes', 'dados_publicos',
		'imagem_perfil','imagem_capa','chakra'
	);


	/*VALIDAÇÃO DOS CADASTROS*/
	public static $rules = array(
		'first_name'      => 'required',
		'last_name'       => 'required',
		'sexo'            => 'required',
		'estado_civil'    => 'required',
		// 'peso'            => 'required',
		// 'altura'          => 'required',
		'nacionalidade'   => 'required',
		'telefone'        => 'required',
		'endereco'        => 'required',
		'objetivos'       => 'required',
		'data_nascimento' => 'required',
	);

	/*TRANSFORMAÇÃO DAS DATAS*/
	public function getDates()
	{
		return array('created_at','updated_at','data_nascimento','inicio_infinito','inicio_yoga');
	}

	/*** PROPRIEDADES ESPECIAIS ****/
	public function setInicioYogaAttribute($value)
	{
		$this->attributes['inicio_yoga'] = Carbon::createFromFormat('d/m/Y', $value);
	}

	public function setInicioInfinitoAttribute($value)
	{
		$this->attributes['inicio_infinito'] = Carbon::createFromFormat('d/m/Y', $value);
	}

	public function setDataNascimentoAttribute($value)
	{
		$this->attributes['data_nascimento'] = Carbon::createFromFormat('d/m/Y', $value);
	}

	public function getNomeCompletoAttribute()
	{
		return $this->first_name . " " . $this->last_name;
	}

	public function getSexoNomeAttribute()
	{
		$opcoes = Config::get('infinito.sexo');
		if ( isset( $opcoes[ $this->sexo ] ) ) return $opcoes[ $this->sexo ];
		return "";
	}

	public function getEstadoCivilNomeAttribute()
	{
		$opcoes = Config::get('infinito.estado_civil');
		if ( isset( $opcoes[ $this->estado_civil ] ) ) return $opcoes[ $this->estado_civil ];
		return "";
	}

	public function getNacionalidadeNomeAttribute()
	{
		$opcoes = Config::get('infinito.nacionalidade');
		if ( isset( $opcoes[ $this->nacionalidade ] ) ) return $opcoes[ $this->nacionalidade ];
		return "";
	}

	/*** RELACIONAMENTOS ****/
	public function albuns()
	{
		return $this->hasMany('Album');
	}

	public function professor()
	{
		return $this->hasOne('User', 'id', 'professor_id');
	}

	public function alunos()
	{
		return $this->hasMany('User', 'professor_id');
	}

	public function chakras()
	{
		return $this->hasMany('Chakra','professor_id');
	}

	public function eventos()
	{
		return $this->hasMany('Evento','aluno_id');
	}

	public function metas()
	{
		return $this->hasMany('Meta','aluno_id');
	}

	public function tecnicas()
	{
		return $this->belongsToMany('Tecnica','tecnicas_user','user_id','tecnica_id');
	}

	public function historicos()
	{
		return $this->hasMany('Historico','user_id');
	}

	/*** AUXILIARES ****/
	public function isProfessor()
	{
		$permissoes = $this->getMergedPermissions();
		if ( isset( $permissoes['aluno'] ) && $permissoes['aluno'] ) {
			return true;
		}

		return false;
	}

	/*** AUXILIARES ****/
	public function isAdmin()
	{
		$permissoes = $this->getMergedPermissions();
		if ( isset( $permissoes['admin'] ) && $permissoes['admin'] ) {
			return true;
		}

		return false;
	}
}

app/controllers/MensagensController.php
<?php

class MensagensController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$conversas = Conversa::where('autor_id','=',$this->user->id)->orWhere('destino_id','=',$this->user->id)->orderBy('updated_at','DESC')->orderBy('created_at','DESC')->paginate(20);

		return Response::view('mensagens.index',["conversas" => $conversas]);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$validator = Validator::make(Input::all(), [
			"from" => "required",
			"to" => "required",
			"mensagem" => "required",
			"assunto" => "required",
		]);

		$retorno = Input::get('retorno');

		if ($validator->fails()) {
			return Redirect::to( $retorno )->withErrors($validator)->withInput( Input::all() );
		} else {

			$conversa = Conversa::create([
				"assunto" => Input::get("assunto"),
			]);

			$autor = User::find( Input::get("from") );
			$destino = User::find( Input::get("to") );

			$conversa->autor()->associate($autor);
			$conversa->destino()->associate( $destino );
			$conversa->save();


			$mensagem = Mensagem::create([
				"texto" => Input::get("mensagem")
			]);

			$conversa->mensagens()->save($mensagem);
			$mensagem->conversa()->associate($conversa);
			$mensagem->autor()->associate($autor);

			$mensagem->save();

			$this->createHistorico(
				"Nova mensagem! <a href='" . route("mensagens.index") . "'>" . $conversa->assunto . "</a>",
				"envelope",
				$destino
			);

			// dd( $mensagem->toArray() );

			return Redirect::to($retorno)->with("message_nota","Mensagem enviada com sucesso");
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$conversa = Conversa::find($id);

		if ( $conversa ) {
			$conversa->load('mensagens');
			$conversa->mensagens->sortBy('created_at');
			
			return Response::view('mensagens.form',["conversa" => $conversa]);
		} else {
			App::abort(404);
		}

	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$cid = Input::get("conversa");

		$conversa = Conversa::find($cid);

		if ( ! $conversa ) {
			return Redirect::route("mensagens.index")->with("message","A conversa não existe");
		}

		$validator = Validator::make(Input::all(), [
			"from" => "required",
			"to" => "required",
			"mensagem" => "required",
		]);

		if ($validator->fails()) {
			return Redirect::route("mensagens.show", [$conversa->id])->withErrors($validator)->withInput( Input::all() );
		} else {

			$mensagem = Mensagem::create([
				"texto" => Input::get("mensagem")
			]);

			$destino = User::find( Input::get("from") );

			$conversa->mensagens()->save($mensagem);
			$mensagem->conversa()->associate($conversa);
			$mensagem->autor()->associate( $destino );

			$mensagem->save();

			$this->createHistorico(
				"Nova mensagem! <a href='" . route("mensagens.index") . "'>" . $conversa->assunto . "</a>",
				"envelope",
				$destino
			);

			return Redirect::route("mensagens.show", [$conversa->id])->with("message","Mensagem enviada com sucesso");
		}

		return $this->index();
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


}

app/views/mensagens/form.blade.php
@extends('master')

@section('content')
	<div class="row mensagens">
		<div class="col-xs-12 col-sm-8 col-sm-offset-2">
			@include('usuarios.imagens')

			<div class="row">
				<h1 class="tit-area col-xs-12 col-sm-8">Mensagens</h1>
				<div class="col-xs-12 col-sm-4 text-right">
					<a href="{{ route('mensagens.index') }}"><i class="glyphicon glyphicon-chevron-left"></i> Voltar</a>
				</div>
			</div>

			<div class="conteudo-container row">
				<div class="col-xs-12">
					<div class="cabecalho">
						<div class="row">
							<span class="info info-de col-xs-12 col-sm-4">De: 
							@if($conversa->autor)
								<a href="{{ route('usuarios.show', [$conversa->autor->id]) }}">{{ $conversa->autor->nome_completo }}</a>
							@else
								Não identificado
							@endif
							</span>
							<span class="info info-assunto col-xs-12 col-sm-4">Assunto: {{ $conversa->assunto }}</span>
							<span class="info info-data col-xs-12 col-sm-4 text-right">Data: {{ date( 'd/m/Y H:i', strtotime($conversa->updated_at)) }}</span>
						</div>
					</div>
				</div>
				@foreach ( $conversa->mensagens  as $m)
					@if ( $m->autor )
						{{-- expr --}}
						@if ( $m->autor->id == $usuario->id )
							<div class="col-xs-12 col-sm-10 corpo">
						@else
							<div class="col-xs-12 col-sm-10 col-sm-offset-2 corpo resposta">
						@endif
						<p class="mensagem-data">{{ $m->autor->nome_completo }} - {{ date( 'd/m/Y H:i', strtotime($m->created_at)) }}</p>

					@else
						<div class="col-xs-12 col-sm-10 col-sm-offset-2 corpo resposta">
						<p class="mensagem-data">Não identificado - {{ date( 'd/m/Y H:i', strtotime($m->created_at)) }}</p>
					@endif

						<p>{{ nl2br($m->texto) }}</p>
					</div>
				@endforeach

				{{ Form::open( [ "route" => "mensagens.update", "method" => "PUT" ] ) }}
					{{ Form::hidden('conversa', $conversa->id) }}

					@if ( $conversa->autor->id == $usuario->id  )
						{{ Form::hidden('from', $usuario->id) }}
						{{ Form::hidden('to', $conversa->destino->id) }}
					@else
						{{ Form::hidden('from', $usuario->id) }}
						{{ Form::hidden('to', $conversa->autor->id) }}
					@endif

				<div class="col-xs-12 form-group">
					{{ Form::textarea('mensagem', '', ['rows' => 5, 'class' => 'form-control'] ) }}
				</div>
				<div class="col-xs-12">
					<button class="btn btn-primary pull-right">Enviar resposta</button>
				</div>
				{{ Form::close() }}
			</div>
		</div>
	</div>
@stop

app/views/mensagens/index.blade.php
@extends('master')

@section('content')
	<div class="row">
		<div class="col-xs-12 col-sm-8 col-sm-offset-2">
			@include('usuarios.imagens')

			<h1>Mensagens</h1>

			<div class="conteudo-container row">
				<div class="col-xs-12">
					{{ Form::open(array('route' => 'usuarios.index', 'method' => 'GET')) }}
					{{ Form::label('q','Buscar') }}<br>
					{{ Form::text('q','') }}
					<button class="btn btn-link"><i class="glyphicon glyphicon-search"></i></button>
					{{ Form::close() }}
				</div>
				<div class="col-xs-12">
					<table class="table table-hover table-condensed table-responsive">
						@foreach ( $conversas  as $conversa)
							<tr>
								<td><b>De:</b> {{ $conversa->autor->nome_completo }}</td>
								<td><b>Assunto:</b> <a href="{{ route('mensagens.show', [$conversa->id]) }}">{{ $conversa->assunto }}</a></td>
								<td><b>Data:</b> {{ date( 'd/m/Y H:i', strtotime($conversa->updated_at)) }}</td>
							</tr>
						@endforeach
					</table>
				</div>
			</div>
		</div>
	</div>
@stop