app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Route::group(array("before" => "auth"), function()
{
	Route::get('/', 					["as" => "home", 		"uses" => "HomeController@index"]);

	Route::resource('usuarios', 	'UsuarioController');
	Route::resource('mensagens', 	'MensagensController');
	// Route::resource('fotos', 	'FotosController');
	Route::resource('videos', 		'VideosController');
	Route::resource('metas', 		'MetasController');
	Route::resource('performance',  'PerformanceController');
	Route::resource('eventos', 		'EventosController');

	Route::get('usuarios/{id}/professor/{opcao}', 				[ 'as' => 'usuarios.professor', 'uses' => 'UsuarioController@professor']);

	Route::get('fotos', 										[ 'as' => 'fotos.index', 'uses' => 'FotosController@index']);
	Route::get('fotos/album/{id?}', 							[ 'as' => 'fotos.album', 'uses' => 'FotosController@album']);
	Route::post('salva-foto/{tipo}', 							[ 'as' => 'usuario.fotos', 'uses' => 'UsuarioController@salvaFoto']);

	Route::get( 'conhecimento/aluno/{id}', 						[ 'as' => 'performance.aluno', 'uses' => 'PerformanceController@aluno']);
	Route::post('conhecimento/aluno/{id}', 						[ 'as' => 'performance.alunoUpdate', 'uses' => 'PerformanceController@alunoUpdate']);
	Route::get( 'conhecimento/chakra/{aid}/{cid}', 				[ 'as' => 'performance.chakra', 'uses' => 'PerformanceController@show']);
	Route::get( 'conhecimento/chakra/{aid}/{cid}/edit', 		[ 'as' => 'performance.chakra.edit', 'uses' => 'PerformanceController@edit']);
	Route::put( 'conhecimento/chakra/{aid}/{cid}', 				[ 'as' => 'performance.chakra.update', 'uses' => 'PerformanceController@update']);
	Route::post('conhecimento/chakra/{cid}/tecnica', 			[ 'as' => 'performance.chakra.tecnicac', 'uses' => 'PerformanceController@createTecnica']);
	Route::put( 'conhecimento/chakra/{cid}/tecnica/{tid}', 		[ 'as' => 'performance.chakra.tecnicau', 'uses' => 'PerformanceController@updateTecnica']);
	Route::delete('conhecimento/chakra/{cid}/tecnica/{tid}', 	[ 'as' => 'performance.chakra.tecnicad', 'uses' => 'PerformanceController@deleteTecnica']);
	Route::post('conhecimento/chakra/aluno/tecnicas/', 			[ 'as' => 'performance.chakra.tecAluno', 'uses' => 'PerformanceController@tecAluno']);

	Route::get('eventos/calendar/{aid?}', 						[ 'as' => 'eventos.calendar', 'uses' => 'EventosController@calendar']);
	Route::get('eventos/create/{aid?}', 						[ 'as' => 'eventos.createc', 'uses' => 'EventosController@create']);
	Route::get('eventos/edit/{aid}/{id}', 						[ 'as' => 'eventos.editc', 'uses' => 'EventosController@edit']);

	Route::get( 'performance/aluno/{aid?}', 					[ 'as' => 'metas.aluno', 'uses' => 'MetasController@aluno']);
	Route::get( 'performance/create/{tipo}/{aid?}', 			[ 'as' => 'metas.criar', 'uses' => 'MetasController@create']);
	Route::post('performance/{id}/add-foto', 					[ 'as' => 'metas.add-foto', 'uses' => 'MetasController@addFoto']);
	Route::post('performance/{id}/add-nota', 					[ 'as' => 'metas.add-nota', 'uses' => 'MetasController@addNota']);
});

/* ROTAS DE LOGIN, SENHA E CADASTRO */
Route::get('/login', 					["as" => "login", 			"uses" => "LoginController@index"]);
Route::post('/login', 					["as" => "login.validate", 	"uses" => "LoginController@validate"]);
Route::get('/esqueci-a-senha', 			["as" => "login.esqueci", 	"uses" => "LoginController@esqueci"]);
Route::post('/esqueci-a-senha', 		["as" => "login.senha", 	"uses" => "LoginController@enviaSenha"]);
Route::get('/senha/{id}/{token}', 		["as" => "login.reset", 	"uses" => "LoginController@formSenha"]);
Route::post('/senha', 					["as" => "login.atualiza", 	"uses" => "LoginController@validaSenha"]);
Route::get('/logout', 					["as" => "logout", 			"uses" => "LoginController@logout"]);
Route::get('/cadastro', 				["as" => "cadastro", 		"uses" => "LoginController@cadastro"]);
Route::post('/cadastro', 				["as" => "cadastro.save", 	"uses" => "LoginController@cadastroSave"]);

app/models/Video.php
<?php

use Carbon\Carbon;

class Video extends Eloquent {

	protected $fillable = array('nome', 'url');

	/*VALIDAÇÃO DOS CADASTROS*/
	public static $rules = array(
		'url'  => 'required',
	);

	/*TRANSFORMAÇÃO DAS DATAS*/
	public function getDates()
	{
		return array('created_at','updated_at');
	}

	public function users()
	{
		return $this->belongsToMany('User', 'videos_users');
	}
}

app/controllers/VideosController.php
<?php

class VideosController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$videos = Video::orderBy('created_at','DESC')->paginate(20);
		$ids = [];
		$str = "";

		foreach ($videos as $v) {
			parse_str( parse_url( $v->url, PHP_URL_QUERY ), $tmp );
			if ( isset( $tmp['v'] ) && ! empty( $tmp['v'] ) ) {
				$ids[ $tmp['v'] ] = $v;
				$str .= ( ! empty($str) ? "," : "" ) . $tmp['v'];
			}
		}

		$dados = $this->youtubeData( $str );

		// dd($dados);
		
		foreach ($dados as $key => $value) {
			$o = $ids[ $value['id'] ];

			if ( is_object($o) ) {
				$ids[$value['id']] = [
					"id" => $o->id,
					"yid" => $value['id'],
					"title" => $value['snippet']['title'],
					"views" => $value['statistics']['viewCount'],
				];
			}
		}

		return Response::view('videos.index', [
			"videos" => $ids,
			"query"  => $videos
		]);
	}

	function youtubeData($id) {
		$url = "https://www.googleapis.com/youtube/v3/videos?id=" . $id . "&key=" . Config::get('infinito.YT_KEY') . "&fields=items(id,snippet(title),statistics)&part=snippet,statistics";

		$videoData = file_get_contents($url);

		if ($videoData) {
			$json = json_decode($videoData, true);

			return $json['items'];
		} else {
			return false;
		}
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$validator = Validator::make(Input::all(), array(
			'url' => 'required|unique:videos,url',
		));

		if ($validator->fails())
		{
			return Redirect::to("videos")->withErrors($validator)->withInput( Input::all() );
		}
		else
		{
			$url = Input::get("url");

			Video::create([
				"url" => $url,
				"nome" => uniqid()
			]);

			return $this->index();
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Video::destroy($id);

		return Response::make(json_encode(["sucesso" => true]));
	}


}

app/views/videos/index.blade.php
@extends('master')

@section('content')
	<div class="videos row">
		<div class="col-xs-12 col-sm-8 col-sm-offset-2">
			<h1 class="tit-area">Vídeos</h1>

			<div class="conteudo-container row">
				
				@if( $usuario->isProfessor() )
				<div class="col-xs-12">
					<a href="#formVideo" class="btn btn-primary btn-enviar-video fancybox">Enviar Vídeo</a>
				</div>
				@endif

				<div class="col-xs-12">
					<table class="tabela-videos row">
						<tr>
							<?php $i=1; ?>
							@foreach ($videos as $v)
								<td class="col-xs-6 col-sm-3" valign="top">
									<p>
										<a class="fancybox fancybox.iframe" href="http://youtube.com/v/{{ $v['yid'] }}">
											<img src="http://img.youtube.com/vi/{{ $v['yid'] }}/mqdefault.jpg" class="thumb-video">
											{{ str_limit($v['title'], 48, ' ...') }}
										</a><br>
										{{ $v['views'] }} Visualizações
									</p>

									@if( $usuario->isProfessor() )
									<p class="text-center"><a href="{{ route('videos.destroy', [$v['id']]) }}" class="btn-excluir-video">Excluir</a></p>
									@endif
								</td>

								@if ($i++ % 4 == 0)
									</tr><tr>
								@endif
							@endforeach

							@if ( $i < 4 )
								@while ( $i++ < 4 )
									<td></td>
								@endwhile
							@endif

					</table>
				</div>
				<div class="col-xs-12">
					{{ $query->links() }}
				</div>
			</div>
		</div>
	</div>

	@if( $usuario->isProfessor() )
	<div id="formVideo" class="esconde">
		{{ Form::open(array('url' => '/videos', 'method' => 'POST') )}}
		{{ Form::hidden('retorno', Route::getCurrentRoute()->getUri() ); }}
		<h2>URL do vídeo no Youtube:</h2>

		<div class="form-group">
			{{ Form::text('url', "", ['class' => 'form-control']) }}
		</div>

		<div class="form-group text-right">
			{{ Form::submit('Enviar', ['class' => 'btn btn-primary']); }}
			<button type="button" class="btn btn-primary btn-cancelar">Cancelar</button>
		</div>
		{{ Form::close() }}
	</div>
	@endif
@stop