app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Route::group(array("before" => "auth"), function()
{
	Route::get('/', 					["as" => "home", 		"uses" => "HomeController@index"]);

	Route::resource('usuarios', 	'UsuarioController');
	Route::resource('mensagens', 	'MensagensController');
	// Route::resource('fotos', 	'FotosController');
	Route::resource('videos', 		'VideosController');
	Route::resource('metas', 		'MetasController');
	Route::resource('performance',  'PerformanceController');
	Route::resource('eventos', 		'EventosController');

	Route::get('usuarios/{id}/professor/{opcao}', 				[ 'as' => 'usuarios.professor', 'uses' => 'UsuarioController@professor']);

	Route::get('fotos', 										[ 'as' => 'fotos.index', 'uses' => 'FotosController@index']);
	Route::get('fotos/album/{id?}', 							[ 'as' => 'fotos.album', 'uses' => 'FotosController@album']);
	Route::post('salva-foto/{tipo}', 							[ 'as' => 'usuario.fotos', 'uses' => 'UsuarioController@salvaFoto']);

	Route::get( 'conhecimento/aluno/{id}', 						[ 'as' => 'performance.aluno', 'uses' => 'PerformanceController@aluno']);
	Route::post('conhecimento/aluno/{id}', 						[ 'as' => 'performance.alunoUpdate', 'uses' => 'PerformanceController@alunoUpdate']);
	Route::get( 'conhecimento/chakra/{aid}/{cid}', 				[ 'as' => 'performance.chakra', 'uses' => 'PerformanceController@show']);
	Route::get( 'conhecimento/chakra/{aid}/{cid}/edit', 		[ 'as' => 'performance.chakra.edit', 'uses' => 'PerformanceController@edit']);
	Route::put( 'conhecimento/chakra/{aid}/{cid}', 				[ 'as' => 'performance.chakra.update', 'uses' => 'PerformanceController@update']);
	Route::post('conhecimento/chakra/{cid}/tecnica', 			[ 'as' => 'performance.chakra.tecnicac', 'uses' => 'PerformanceController@createTecnica']);
	Route::put( 'conhecimento/chakra/{cid}/tecnica/{tid}', 		[ 'as' => 'performance.chakra.tecnicau', 'uses' => 'PerformanceController@updateTecnica']);
	Route::delete('conhecimento/chakra/{cid}/tecnica/{tid}', 	[ 'as' => 'performance.chakra.tecnicad', 'uses' => 'PerformanceController@deleteTecnica']);
	Route::post('conhecimento/chakra/aluno/tecnicas/', 			[ 'as' => 'performance.chakra.tecAluno', 'uses' => 'PerformanceController@tecAluno']);

	Route::get('eventos/calendar/{aid?}', 						[ 'as' => 'eventos.calendar', 'uses' => 'EventosController@calendar']);
	Route::get('eventos/create/{aid?}', 						[ 'as' => 'eventos.createc', 'uses' => 'EventosController@create']);
	Route::get('eventos/edit/{aid}/{id}', 						[ 'as' => 'eventos.editc', 'uses' => 'EventosController@edit']);

	Route::get( 'performance/aluno/{aid?}', 					[ 'as' => 'metas.aluno', 'uses' => 'MetasController@aluno']);
	Route::get( 'performance/create/{tipo}/{aid?}', 			[ 'as' => 'metas.criar', 'uses' => 'MetasController@create']);
	Route::post('performance/{id}/add-foto', 					[ 'as' => 'metas.add-foto', 'uses' => 'MetasController@addFoto']);
	Route::post('performance/{id}/add-nota', 					[ 'as' => 'metas.add-nota', 'uses' => 'MetasController@addNota']);
});

/* ROTAS DE LOGIN, SENHA E CADASTRO */
Route::get('/login', 					["as" => "login", 			"uses" => "LoginController@index"]);
Route::post('/login', 					["as" => "login.validate", 	"uses" => "LoginController@validate"]);
Route::get('/esqueci-a-senha', 			["as" => "login.esqueci", 	"uses" => "LoginController@esqueci"]);
Route::post('/esqueci-a-senha', 		["as" => "login.senha", 	"uses" => "LoginController@enviaSenha"]);
Route::get('/senha/{id}/{token}', 		["as" => "login.reset", 	"uses" => "LoginController@formSenha"]);
Route::post('/senha', 					["as" => "login.atualiza", 	"uses" => "LoginController@validaSenha"]);
Route::get('/logout', 					["as" => "logout", 			"uses" => "LoginController@logout"]);
Route::get('/cadastro', 				["as" => "cadastro", 		"uses" => "LoginController@cadastro"]);
Route::post('/cadastro', 				["as" => "cadastro.save", 	"uses" => "LoginController@cadastroSave"]);

app/models/User.php
<?php

use Carbon\Carbon;

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends \Cartalyst\Sentry\Users\Eloquent\User implements RemindableInterface {

	use UserTrait, RemindableTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	protected static $loginAttribute = 'email';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array(
		'password',
		'reset_password_code',
		'activation_code',
		'persist_code',
		'remember_token',
	);

	protected $fillable = array(
		'email', 'professor_id','password','first_name', 'last_name', 'sexo', 'profissao', 'peso', 'altura', 'nacionalidade', 'telefone',
		'estado_civil', 'endereco', 'telefone', 'nacionalidade', 'objetivos', 'facebook',
		'data_nascimento', 'inicio_infinito', 'inicio_yoga', 'observacoes', 'dados_publicos',
		'imagem_perfil','imagem_capa','chakra'
	);


	/*VALIDAÇÃO DOS CADASTROS*/
	public static $rules = array(
		'first_name'      => 'required',
		'last_name'       => 'required',
		'sexo'            => 'required',
		'estado_civil'    => 'required',
		// 'peso'            => 'required',
		// 'altura'          => 'required',
		'nacionalidade'   => 'required',
		'telefone'        => 'required',
		'endereco'        => 'required',
		'objetivos'       => 'required',
		'data_nascimento' => 'required',
	);

	/*TRANSFORMAÇÃO DAS DATAS*/
	public function getDates()
	{
		return array('created_at','updated_at','data_nascimento','inicio_infinito','inicio_yoga');
	}

	/*** PROPRIEDADES ESPECIAIS ****/
	public function setInicioYogaAttribute($value)
	{
		$this->attributes['inicio_yoga'] = Carbon::createFromFormat('d/m/Y', $value);
	}

	public function setInicioInfinitoAttribute($value)
	{
		$this->attributes['inicio_infinito'] = Carbon::createFromFormat('d/m/Y', $value);
	}

	public function setDataNascimentoAttribute($value)
	{
		$this->attributes['data_nascimento'] = Carbon::createFromFormat('d/m/Y', $value);
	}

	public function getNomeCompletoAttribute()
	{
		return $this->first_name . " " . $this->last_name;
	}

	public function getSexoNomeAttribute()
	{
		$opcoes = Config::get('infinito.sexo');
		if ( isset( $opcoes[ $this->sexo ] ) ) return $opcoes[ $this->sexo ];
		return "";
	}

	public function getEstadoCivilNomeAttribute()
	{
		$opcoes = Config::get('infinito.estado_civil');
		if ( isset( $opcoes[ $this->estado_civil ] ) ) return $opcoes[ $this->estado_civil ];
		return "";
	}

	public function getNacionalidadeNomeAttribute()
	{
		$opcoes = Config::get('infinito.nacionalidade');
		if ( isset( $opcoes[ $this->nacionalidade ] ) ) return $opcoes[ $this->nacionalidade ];
		return "";
	}

	/*** RELACIONAMENTOS ****/
	public function albuns()
	{
		return $this->hasMany('Album');
	}

	public function professor()
	{
		return $this->hasOne('User', 'id', 'professor_id');
	}

	public function alunos()
	{
		return $this->hasMany('User', 'professor_id');
	}

	public function chakras()
	{
		return $this->hasMany('Chakra','professor_id');
	}

	public function eventos()
	{
		return $this->hasMany('Evento','aluno_id');
	}

	public function metas()
	{
		return $this->hasMany('Meta','aluno_id');
	}

	public function tecnicas()
	{
		return $this->belongsToMany('Tecnica','tecnicas_user','user_id','tecnica_id');
	}

	public function historicos()
	{
		return $this->hasMany('Historico','user_id');
	}

	/*** AUXILIARES ****/
	public function isProfessor()
	{
		$permissoes = $this->getMergedPermissions();
		if ( isset( $permissoes['aluno'] ) && $permissoes['aluno'] ) {
			return true;
		}

		return false;
	}

	/*** AUXILIARES ****/
	public function isAdmin()
	{
		$permissoes = $this->getMergedPermissions();
		if ( isset( $permissoes['admin'] ) && $permissoes['admin'] ) {
			return true;
		}

		return false;
	}
}

app/controllers/UsuarioController.php
<?php

class UsuarioController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$professor = Input::get('p');
		$busca = Input::get('q');

		if ( $professor && ! empty( $professor ) ) {
			$usuarios = User::where('professor_id','=', $professor)->orderBy('first_name','ASC')->orderBy('last_name','ASC');
			# code...
		} else {
			$usuarios = User::orderBy('first_name','ASC')->orderBy('last_name','ASC');
		}

		if ( $busca && ! empty( $busca ) ) {
			$usuarios = $usuarios->where('first_name', 'LIKE', "%$busca%")->orWhere('last_name','LIKE',"%$busca%");
		}

		$usuarios = $usuarios->paginate(20);


		// dd( $usuarios->toArray() );

		return Response::view('usuarios.index',[
			"usuarios" => $usuarios
		]);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$perfil = User::find($id);

		if ( $perfil ) {
			$perfil->load('professor');
			return Response::view('usuarios.perfil',[
				"perfil" => $perfil
			]);
		} else {
			App::abort(404);
		}
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$perfil = User::find($id);

		if ( $perfil ) {
			$profissoes = Config::get('infinito.profissoes', []);
			$profissoes = array_combine($profissoes, $profissoes);
			asort($profissoes);

			$profissoes[] = "Outros";

			return Response::view('usuarios.form',[
				"perfil"     => $perfil,
				"profissoes" => $profissoes,
			]);
		} else {
			App::abort(404);
		}
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$perfil = User::find($id);

		if ( $perfil ) {

			$validator = Validator::make(Input::all(), User::$rules);

			if ($validator->fails()) {
				return Redirect::route("usuarios.edit", [$perfil->id])->withErrors($validator)->withInput( Input::all() );
			} else {

				$perfil->fill( Input::all() );
				$perfil->cadastro_completo = true;
				$perfil->save();

				return Redirect::route("usuarios.show", [$perfil->id])->with("message","Dados atualizados com sucesso");
			}
		} else {
			App::abort(404);
		}
	}


	/**
	 * Atualiza grupo de professor do usuario
	 *
	 * @param  int  $id
	 * @param  bool  $opcao
	 * @return Response
	 */
	public function professor($id, $opcao)
	{
		$perfil = User::find($id);

		if ( $perfil ) {

			if ( ! $this->user->isAdmin() ) {
				return Redirect::route("usuarios.show", [$perfil->id])->with("message","Você não tem permissão para fazer essa alteração");
			}

			$gProf = Sentry::findGroupByName('professor');

			if ( $opcao ) {
				$perfil->addGroup($gProf);
			} else {
				$perfil->removeGroup($gProf);
			}

			return Redirect::route("usuarios.show", [$perfil->id])->with("message","Perfil atualizados com sucesso");
		} else {
			App::abort(404);
		}
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


	public function salvaFoto($tipo)
	{
		$retorno = Input::get('retorno');

		// dd($tipo);

		if ( ! Input::hasFile('imagem')) {
			return Redirect::to($retorno . "?image-error-$tipo=true");
		} else {
			$foto     = Input::file('imagem');
			$destino  = Config::get("infinito.UPLOAD_PATH");
			$fileName = $tipo . "_" . $this->user->id . "_" . uniqid() . "." . $foto->getClientOriginalExtension();

			$foto->move($destino, $fileName);

			if ( $tipo == "capa" ) {
				$this->user->imagem_capa = $fileName;
			} else {
				$this->user->imagem_perfil = $fileName;
			}
			$this->user->save();

			return Redirect::to($retorno);
		}
	}


}

app/views/usuarios/imagens.blade.php
<div class="row">
	<div class="imagens-perfil">
		<div class="capa" style="background-image: url('/uploads/{{ $perfil->imagem_capa }}')">
			@if( ! empty( $perfil->imagem_capa ) )
				{{-- <img src="/uploads/{{ $perfil->imagem_capa }}" alt="{{ $perfil->nome_completo }}"> --}}
				{{-- <img src="{{ Image::url('/uploads/' . $perfil->imagem_capa, 780, 200,['crop']) }}" alt="{{ $perfil->nome_completo }}"> --}}
			@endif
			@if ( $usuario->id == $perfil->id )
				<a href="#formFotoCapa" class="btn-trocar-imagem btn-imagem-capa fancybox"><i class="glyphicon glyphicon-pencil"></i></a>
			@endif
		</div>
		<div class="perfil" style="background-image: url('{{ $perfil->imagem_perfil ? "/uploads/" . $perfil->imagem_perfil : "/img/no-avatar.gif" }}')">
			@if( empty( $perfil->imagem_perfil ) )
				{{-- <img src="/img/no-avatar.gif" alt="{{ $perfil->first_name . " " . $perfil->last_name }}"> --}}
			@else
				{{-- <img src="{{ '/uploads/' . $perfil->imagem_perfil }}" alt="{{ $perfil->nome_completo }}"> --}}
				{{-- <img src="{{ Image::url('/uploads/' . $perfil->imagem_perfil ,150,150,['crop']) }}" alt="{{ $perfil->nome_completo }}"> --}}

			@endif
			@if ( $usuario->id == $perfil->id )
				<a href="#formFotoPerfil" class="btn-trocar-imagem btn-imagem-perfil fancybox"><i class="glyphicon glyphicon-pencil"></i></a>
			@endif
		</div>
	</div>
</div>

@if ( $usuario->id == $perfil->id )
	<div id="formFotoPerfil" class="esconde">
		{{ Form::open(array('url' => '/salva-foto/perfil', 'files' => true)) }}
		{{ Form::hidden('retorno', Route::getCurrentRoute()->getUri() ); }}
		<h2>Escolha uma foto para seu perfil:</h2>

		@if ( Input::get('image-error-perfil','false') == 'true' )
			<div class="form-group has-error">
				{{ Form::file('imagem', ['class' => 'form-control']) }}
				<label for="imagem" class="control-label">Formato de imagem inválido</label>
			</div>
		@else
			<div class="form-group">
				{{ Form::file('imagem', ['class' => 'form-control']) }}
			</div>
		@endif

		<div class="form-group">
			{{ Form::submit('Enviar', ['class' => 'btn']); }}
		</div>
		{{ Form::close() }}
	</div>

	<div id="formFotoCapa" class="esconde">
		{{ Form::open(array('url' => '/salva-foto/capa', 'files' => true)) }}
		{{ Form::hidden('retorno', Route::getCurrentRoute()->getUri() ); }}
		<h2>Escolha uma foto para sua capa:</h2>

		@if ( Input::get('image-error-capa','false') == 'true' )
			<div class="form-group has-error">
				{{ Form::file('imagem', ['class' => 'form-control']) }}
				<label for="imagem" class="control-label">Formato de imagem inválido</label>
			</div>
		@else
			<div class="form-group">
				{{ Form::file('imagem', ['class' => 'form-control']) }}
			</div>
		@endif

		<div class="form-group">
			{{ Form::submit('Enviar', ['class' => 'btn']); }}
		</div>
		{{ Form::close() }}
	</div>
@endif

app/views/usuarios/index.blade.php
@extends('master')

@section('content')
	<div class="row">
		<div class="col-xs-12 col-sm-10 col-sm-offset-2">
			<h1>Quem faz parte do Infinito</h1>
		</div>

		<div class="col-xs-12 col-sm-10 col-sm-offset-2">
			<div class="row">
				<div class="col-xs-12 col-sm-10">
					<div class="conteudo-container row">
						<div class="col-xs-12 col-sm-9">
							{{ Form::open(array('route' => 'usuarios.index', 'method' => 'GET')) }}
							{{ Form::hidden('p',Input::get('p')) }}
							{{ Form::label('q','Buscar') }}<br>
							{{ Form::text('q',Input::get('q')) }}
							<button class="btn btn-link"><i class="glyphicon glyphicon-search"></i></button>
							{{ Form::close() }}
						</div>
						<div class="col-xs-12 col-sm-3 text-right">
							@if ( empty( Input::get("p") ) && $usuario->isProfessor() )
								<a href="/usuarios?p={{ $usuario->id }}" class="btn btn-primary">Mostrar meus alunos</a>
							@else
								<a href="/usuarios" class="btn btn-primary">Mostrar todos</a>
							@endif
						</div>
						<div class="col-xs-12">
							<ul class="lista-usuarios list-unstyled row">
								@foreach ($usuarios as $u)
									<li class="col-xs-6 col-sm-3 text-center">
										<a href="{{ route('usuarios.show', [$u->id]) }}" class="thumbnail">
											<div class="perfil"  style="background-image: url('{{ $u->imagem_perfil ? "/uploads/" . $u->imagem_perfil : "/img/no-avatar.gif" }}')">
												{{-- @if( empty( $u->imagem_perfil ) ) --}}
												{{-- <img src="/img/no-avatar.gif" alt="{{ $u->nome_completo }}"> --}}
												{{-- @else --}}
												{{-- <img src="/uploads/{{ $u->imagem_perfil }}" alt="{{ $u->nome_completo }}"> --}}
												{{-- @endif --}}
											</div>
											<p>{{ $u->nome_completo }}</p>
										</a>
									</li>
								@endforeach
							</ul>
						</div>
						<div class="col-xs-12 text-center">
							{{ $usuarios->links() }}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@stop

app/views/usuarios/perfil.blade.php
@extends('master')

@section('content')
	<div class="row">
		<div class="col-xs-12 col-sm-8 col-sm-offset-2">

			@include('usuarios.imagens')

			<h1>{{ $perfil->nome_completo }}</h1>

			@if ( $usuario->id == $perfil->id )
			<p>Dados / <a href="{{ route('usuarios.edit', [$perfil->id]) }}">Editar</a></p>
			@endif

			@if ( Session::has("message") )
				<div class="alert alert-info" role="alert">{{ Session::pull("message") }}</div>
			@endif

			@if ( $errors->has() )
			<div class="alert alert-danger alert-dismissable">
				<i class="fa fa-ban"></i>
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				@foreach( $errors->all('<p>:message</p>') as $message )
					{{ $message }}
				@endforeach
			</div>
			@endif
		</div>

		<div class="col-xs-12 col-sm-10 col-sm-offset-2">
			<div class="row">
				<div class="col-xs-12 col-sm-10">
					<div class="conteudo-container row">
						<div class="col-xs-12 col-sm-9">
							{{-- <p><b>Sexo:</b><br>{{ $perfil->sexo_nome }}</p> --}}
							{{-- <p><b>Estado Civil:</b><br>{{ $perfil->estado_civil_nome }}</p> --}}
							<p><b>Profissão:</b><br>{{ $perfil->profissao }}</p>
							{{-- <p><b>Nacionalidade:</b><br>{{ $perfil->nacionalidade_nome }}</p> --}}
						</div>
					
						<div class="col-xs-12 col-sm-3">
						@if ( $usuario->isAdmin() )
							@if ( $perfil->isProfessor() )
								<a href="{{ route('usuarios.professor',[$perfil->id,0]) }}" class="btn btn-primary btn-block">Tornar não professor</a>
							@else
								<a href="{{ route('usuarios.professor',[$perfil->id,1]) }}" class="btn btn-primary btn-block">Tornar professor</a>
							@endif
						@endif
						@if ( $usuario->isProfessor() && $perfil->professor )
							@if ( $perfil->professor->id == $usuario->id )
								<a href="{{ route('metas.aluno',[$perfil->id]) }}" class="btn btn-primary btn-block">Editar Performance</a>
								<a href="{{ route('performance.aluno', [$perfil->id]) }}" class="btn btn-primary btn-block">Editar Conhecimento</a>
								{{-- <a href="#" class="btn btn-primary btn-block">Editar Calendário</a> --}}
							@endif
						@endif
						@if ( $usuario->isProfessor() )
							<a href="{{ route('eventos.calendar', [$perfil->id]) }}" class="btn btn-primary btn-block">Editar eventos</a>
						@endif
						</div>
					</div>
					
					@if ( $usuario->id != $perfil->id )
					<div class="conteudo-container row">
						<div class="col-xs-12 col-sm-9">
							<p>Envie uma mensagem para {{ $perfil->nome }}:</p>
							{{ Form::open( [ 'route' => 'mensagens.store', 'method' => 'POST' ] ) }}
							{{ Form::hidden('from', $usuario->id) }}
							{{ Form::hidden('to', $perfil->id) }}
							{{ Form::hidden('retorno', Request::url() ); }}
					
							<div class="row">
								<div class="col-xs-12 form-group">
									{{ Form::text('assunto', '', ['placeholder' => 'Assunto:', 'class' => 'form-control'] ) }}
								</div>
								<div class="col-xs-12 form-group">
									{{ Form::textarea('mensagem', '', ['rows' => 5, 'class' => 'form-control'] ) }}
								</div>
								<div class="col-xs-12 form-group">
									<button class="btn btn-primary pull-right">Enviar</button>
								</div>
							</div>
					
							{{ Form::close() }}
						</div>
					</div>
					@endif
				</div>
				@if ( $usuario->id == $perfil->id )
				@include('minicalendar')
				@endif
			</div>
		</div>
	</div>
@stop